#pragma once

#include "CoreMinimal.h"
#include "CommonActivatableWidget.h"
#include "CatanUserSettings.h"
#include "CatanViewTypes.h"

#include "CatanHUDWidget.generated.h"

class UButton;
class UCommonTextBlock;
class UComboBoxString;
class UEditableTextBox;
class UCatanGameSubsystem;
class UCatanNetworkSubsystem;
class UBorder;
class UVerticalBox;
class UScrollBox;
class USizeBox;
class UWidgetSwitcher;
class UWrapBox;
enum class ECatanDevelopmentCard : uint8;

UCLASS()
class CATAN_API UCatanHUDWidget final : public UCommonActivatableWidget
{
    GENERATED_BODY()

public:
    bool IsModalOpen() const;
    void RunHUDGraphSmoke();

protected:
    virtual TSharedRef<SWidget> RebuildWidget() override;
    virtual void NativeConstruct() override;
    virtual void NativeDestruct() override;
    virtual void NativeTick(const FGeometry& MyGeometry, float InDeltaTime) override;

private:
    UPROPERTY(Transient) TObjectPtr<UCatanGameSubsystem> GameSubsystem;
    UPROPERTY(Transient) TObjectPtr<UCatanNetworkSubsystem> NetworkSubsystem;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> PhaseText;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> DiceText;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> PlayersText;
    UPROPERTY(Transient) TObjectPtr<UScrollBox> PlayersScroll;
    UPROPERTY(Transient) TObjectPtr<USizeBox> PlayersListSizeBox;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> HandTitleText;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> DevelopmentHandText;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> DevelopmentAvailabilityText;
    UPROPERTY(Transient) TObjectPtr<UWidgetSwitcher> DevelopmentModeSwitcher;
    UPROPERTY(Transient) TArray<TObjectPtr<UCommonTextBlock>> ResourceCountTexts;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> HintText;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> StatusText;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> EventText;
    UPROPERTY(Transient) TObjectPtr<UBorder> ToastBorder;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> ToastText;
    UPROPERTY(Transient) TObjectPtr<UButton> RollButton;
    UPROPERTY(Transient) TObjectPtr<UButton> SettlementButton;
    UPROPERTY(Transient) TObjectPtr<UButton> RoadButton;
    UPROPERTY(Transient) TObjectPtr<UButton> CityButton;
    UPROPERTY(Transient) TObjectPtr<UButton> BuyCardButton;
    UPROPERTY(Transient) TObjectPtr<UButton> UseCardButton;
    UPROPERTY(Transient) TObjectPtr<UButton> TradeButton;
    UPROPERTY(Transient) TObjectPtr<UButton> PassButton;
    UPROPERTY(Transient) TObjectPtr<UBorder> ModalBorder;
    UPROPERTY(Transient) TObjectPtr<UWidgetSwitcher> ModalSwitcher;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> DropTitle;
    UPROPERTY(Transient) TArray<TObjectPtr<UComboBoxString>> DropInputs;
    UPROPERTY(Transient) TObjectPtr<UButton> ConfirmDropButton;
    UPROPERTY(Transient) TArray<TObjectPtr<UButton>> VictimButtons;
    UPROPERTY(Transient) TObjectPtr<UButton> KnightButton;
    UPROPERTY(Transient) TObjectPtr<UButton> RoadBuildingButton;
    UPROPERTY(Transient) TObjectPtr<UButton> YearOfPlentyButton;
    UPROPERTY(Transient) TObjectPtr<UButton> MonopolyButton;
    UPROPERTY(Transient) TArray<TObjectPtr<UComboBoxString>> PlentyInputs;
    UPROPERTY(Transient) TObjectPtr<UButton> ConfirmPlentyButton;
    UPROPERTY(Transient) TArray<TObjectPtr<UButton>> MonopolyResourceButtons;
    UPROPERTY(Transient) TObjectPtr<UWidgetSwitcher> TradeModeSwitcher;
    UPROPERTY(Transient) TArray<TObjectPtr<UButton>> BankFromButtons;
    UPROPERTY(Transient) TArray<TObjectPtr<UButton>> BankToButtons;
    UPROPERTY(Transient) TArray<TObjectPtr<UComboBoxString>> OfferedInputs;
    UPROPERTY(Transient) TArray<TObjectPtr<UComboBoxString>> RequestedInputs;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> DealText;
    UPROPERTY(Transient) TObjectPtr<UComboBoxString> TradingPlayer;
    UPROPERTY(Transient) TObjectPtr<UButton> AcceptDealButton;
    UPROPERTY(Transient) TObjectPtr<UButton> CancelDealButton;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> WinnerText;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> AvailabilityText;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> BuildCostText;
    UPROPERTY(Transient) TObjectPtr<UComboBoxString> PlayerCount;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> MainPlayerNameText;
    UPROPERTY(Transient) TObjectPtr<UEditableTextBox> SettingsNameInput;
    UPROPERTY(Transient) TObjectPtr<UComboBoxString> SettingsLanguageInput;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> ConfirmationText;
    UPROPERTY(Transient) TObjectPtr<UEditableTextBox> LobbyNameInput;
    UPROPERTY(Transient) TObjectPtr<UEditableTextBox> ManualAddressInput;
    UPROPERTY(Transient) TObjectPtr<UEditableTextBox> DedicatedAddressInput;
    UPROPERTY(Transient) TObjectPtr<UEditableTextBox> DedicatedLobbyTokenInput;
    UPROPERTY(Transient) TObjectPtr<UButton> ResumeDedicatedButton;
    UPROPERTY(Transient) TObjectPtr<UComboBoxString> LobbyResults;
    UPROPERTY(Transient) TArray<TObjectPtr<UCommonTextBlock>> NetworkStatusTexts;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> LobbyPlayersText;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> LobbyAddressText;
    UPROPERTY(Transient) TObjectPtr<UButton> ReadyButton;
    UPROPERTY(Transient) TObjectPtr<UButton> StartLobbyButton;
    UPROPERTY(Transient) TObjectPtr<UButton> LoadLanButton;
    UPROPERTY(Transient) TObjectPtr<UComboBoxString> SavedGameInput;
    TArray<FString> SavedGameSlotIds;
    TArray<bool> SavedGameSlotValid;
    FString SavedGameCatalogDigest;
    UPROPERTY(Transient) TObjectPtr<UButton> CopyLobbyTokenButton;
    UPROPERTY(Transient) TObjectPtr<UWidgetSwitcher> SetupSwitcher;
    UPROPERTY(Transient) TObjectPtr<UBorder> InfoBorder;
    UPROPERTY(Transient) TObjectPtr<UBorder> EventBorder;
    UPROPERTY(Transient) TObjectPtr<UBorder> PlayerBorder;
    UPROPERTY(Transient) TObjectPtr<UBorder> CostBorder;
    UPROPERTY(Transient) TObjectPtr<UVerticalBox> InfoDetails;
    UPROPERTY(Transient) TObjectPtr<UVerticalBox> PlayerDetails;
    UPROPERTY(Transient) TObjectPtr<UButton> LeftDetailsButton;
    UPROPERTY(Transient) TObjectPtr<UButton> RightDetailsButton;
    UPROPERTY(Transient) TObjectPtr<UBorder> ActionBorder;
    UPROPERTY(Transient) TObjectPtr<UCommonTextBlock> ActionTitle;
    UPROPERTY(Transient) TObjectPtr<UWrapBox> ActionButtons;

    FString LastDropPlayer;
    bool bDevelopmentPanelOpen = false;
    bool bTradePanelOpen = false;
    bool bSetupPanelOpen = true;
    bool bActionPanelWasVisible = true;
    FString PreviousToastStatus;
    float ToastRemaining = 0.0f;
    float ResourcePulseRemaining = 0.0f;
    FString PreviousResourceDigest;
    FCatanResourceView PreviousLocalResources;
    bool bHavePreviousLocalResources = false;
    int32 PendingExpensiveAction = 0;
    bool bCompactLayout = false;
    bool bAdaptiveLayoutInitialized = false;
    bool bLeftDetailsOpen = false;
    bool bRightDetailsOpen = false;
    bool bTradeInputsNeedReset = true;
    bool bUIPreviewReported = false;
    bool bAutoLeaveScheduled = false;
    int32 PreviousPlayerStatusCount = INDEX_NONE;
    ECatanResource BankFromSelection = ECatanResource::Wood;
    ECatanResource BankToSelection = ECatanResource::Clay;
    ECatanResource MonopolySelection = ECatanResource::Wood;
    bool bUpdatingPlentyInputs = false;
    FCatanResourceView CurrentBankTradeRates;
    FCatanUserPreferences UserPreferences;
    TArray<TPair<TWeakObjectPtr<UCommonTextBlock>, FString>> LocalizedTexts;

    void BuildLayout();
    void ConfigureComboBox(UComboBoxString* ComboBox, int32 FontSize);
    UCommonTextBlock* AddText(UVerticalBox* Parent, const FString& Text, int32 Size);
    UButton* AddButton(UVerticalBox* Parent, const FString& Label);
    FString Localize(const FString& Key) const;
    void RegisterLocalizedText(UCommonTextBlock* Widget, const FString& Key);
    void ApplyLanguage();
    void RefreshSavedGameOptions();

    UFUNCTION() void Refresh();
    UFUNCTION() void RollDice();
    UFUNCTION() void SelectSettlement();
    UFUNCTION() void SelectRoad();
    UFUNCTION() void SelectCity();
    UFUNCTION() void BuyDevelopmentCard();
    UFUNCTION() void ShowDevelopmentCards();
    UFUNCTION() void ShowTrading();
    UFUNCTION() void PassTurn();
    UFUNCTION() void ConfirmDiscard();
    UFUNCTION() void UpdateDropConfirmation(FString SelectedItem, ESelectInfo::Type SelectionType);
    UFUNCTION() void ChooseVictim0();
    UFUNCTION() void ChooseVictim1();
    UFUNCTION() void ChooseVictim2();
    UFUNCTION() void PlayKnight();
    UFUNCTION() void PlayRoadBuilding();
    UFUNCTION() void ShowYearOfPlentyParameters();
    UFUNCTION() void ShowMonopolyParameters();
    UFUNCTION() void ConfirmYearOfPlenty();
    UFUNCTION() void ConfirmMonopoly();
    UFUNCTION() void CancelDevelopmentParameters();
    UFUNCTION() void UpdatePlentySelection(FString SelectedItem, ESelectInfo::Type SelectionType);
    UFUNCTION() void SelectMonopolyWood();
    UFUNCTION() void SelectMonopolyClay();
    UFUNCTION() void SelectMonopolyHay();
    UFUNCTION() void SelectMonopolySheep();
    UFUNCTION() void SelectMonopolyStone();
    UFUNCTION() void CloseDevelopmentCards();
    UFUNCTION() void TradeWithBank();
    UFUNCTION() void ShowBankTrade();
    UFUNCTION() void ShowPlayerTrade();
    UFUNCTION() void SelectBankFromWood();
    UFUNCTION() void SelectBankFromClay();
    UFUNCTION() void SelectBankFromHay();
    UFUNCTION() void SelectBankFromSheep();
    UFUNCTION() void SelectBankFromStone();
    UFUNCTION() void SelectBankToWood();
    UFUNCTION() void SelectBankToClay();
    UFUNCTION() void SelectBankToHay();
    UFUNCTION() void SelectBankToSheep();
    UFUNCTION() void SelectBankToStone();
    UFUNCTION() void OfferTrade();
    UFUNCTION() void AcceptTrade();
    UFUNCTION() void CancelTrade();
    UFUNCTION() void CloseTrading();
    UFUNCTION() void ReportComboOpening();
    UFUNCTION() void StartNewGame();
    UFUNCTION() void ConfirmNewGame();
    UFUNCTION() void UpdatePlayerCount(FString SelectedItem, ESelectInfo::Type SelectionType);
    UFUNCTION() void ConfirmExpensiveAction();
    UFUNCTION() void CancelExpensiveAction();
    UFUNCTION() void QuitGame();
    UFUNCTION() void HostLanLobby();
    UFUNCTION() void LoadLanLobby();
    UFUNCTION() void UpdateSavedGameSelection(FString SelectedItem, ESelectInfo::Type SelectionType);
    UFUNCTION() void StartBotMatch();
    UFUNCTION() void ShowOnlineSetup();
    UFUNCTION() void ShowLocalNetworkSetup();
    UFUNCTION() void ShowDedicatedServerSetup();
    UFUNCTION() void ShowBotSetup();
    UFUNCTION() void ShowSettings();
    UFUNCTION() void SaveSettings();
    UFUNCTION() void ShowMainSetup();
    UFUNCTION() void FindLanLobbies();
    UFUNCTION() void JoinSelectedLobby();
    UFUNCTION() void JoinManualLobby();
    UFUNCTION() void CreateDedicatedLobby();
    UFUNCTION() void JoinDedicatedLobby();
    UFUNCTION() void ResumeDedicatedLobby();
    UFUNCTION() void CopyDedicatedLobbyToken();
    UFUNCTION() void ToggleLobbyReady();
    UFUNCTION() void StartLobbyMatch();
    UFUNCTION() void LeaveLobby();
    UFUNCTION() void ToggleLeftDetails();
    UFUNCTION() void ToggleRightDetails();

    void ChooseVictim(int32 Index);
    void PlayDevelopmentCard(ECatanDevelopmentCard Card);
    bool GetValidatedPlayerName(FString& OutName);
    void ApplyAdaptiveLayout(bool bCompact);
    void UpdateActionLabels();
    void UpdateActionPanelVisibility();
    void UpdateBankSelectionStyles();
    void UpdateMonopolySelectionStyles();
    void ResetPlentyInputs();
    void UpdatePlayerTradeLimits(const FCatanResourceView& Resources);
    void UpdateDropLimits(const FCatanResourceView& Resources, bool bReset);
    void ResetTradeInputs();
    void ApplyUIPreview();
    void ScheduleAutomatedLobbyLeave(int32 LobbyPlayerCount, bool bLocalHost);
    void SetModalSize(float Width, float Height);
    void SetModalPosition(const FVector2D& Position);
};
